export const bottomInfo: string;
export const description: string;
export const subtitle: string;
export const bottomInfoButtonText: string;
export const downloadBar: string;
export const withCheckbox: string;
export const checkbox: string;
export const checkboxTicked: string;
export const share: string;
